server:
  port: 9921

spring:
  banner:
    location: classpath:/config/banner-dev.txt

  application:
    name: PLANTAS-SERVICE

  datasource:
    url: jdbc:mysql://147.79.86.1:55462/plantas_db?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: RyeD0H45diKTOyE3kzPa

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: none

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB

  jackson:
    time-zone: America/Argentina/Buenos_Aires

path:
  file-server:
    uri: /Users/pablorodas

logging:
  level:
    org.springframework.web: debug
    root: info
    com.netflix.discovery: INFO
  pattern:
    console: "%d{ISO8601} %highlight(%-5level) [%thread] %yellow(%logger{100}) : %msg%n%throwable"